package org.bill.android.myapplication.membershipService;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.5.7.1
//
// Created by Quasar Development at 27/06/2016
//
//---------------------------------------------------



public interface RIVIServiceEvents
{
    public void Starting();
    public void Completed(RIVOperationResult result);
}
