package org.bill.android.myapplication.membershipService;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.5.7.1
//
// Created by Quasar Development at 27/06/2016
//
//---------------------------------------------------



public class RIVOperationResult< T>
{
    public java.lang.Exception Exception;
    public T Result;
    public java.lang.Object Tag;
    public java.lang.String MethodName;
}
