package org.bill.android.myapplication.membershipService;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.5.7.1
//
// Created by Quasar Development at 27/06/2016
//
//---------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;

public class RIVResultHeader extends AttributeContainer implements KvmSerializable
{

    
    public Integer ResultId;
    
    public String ResultMessage;
    
    public Boolean IsSuccess;
    
    public Integer ResultCode;

    public RIVResultHeader ()
    {
    }

    public RIVResultHeader (java.lang.Object paramObj,RIVExtendedSoapSerializationEnvelope __envelope)
    {
	    
	    if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;


        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                //if you have compilation error here, please use a ksoap2.jar and ExKsoap2.jar from libs folder (in the generated zip file)
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                java.lang.Object obj = info.getValue(); 
                if (info.name.equals("ResultId"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.ResultId = Integer.parseInt(j.toString());
                            }
                        }
                        else if (obj instanceof Integer){
                            this.ResultId = (Integer)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("ResultMessage"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.ResultMessage = j.toString();
                            }
                        }
                        else if (obj instanceof String){
                            this.ResultMessage = (String)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("IsSuccess"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.IsSuccess = new Boolean(j.toString());
                            }
                        }
                        else if (obj instanceof Boolean){
                            this.IsSuccess = (Boolean)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("ResultCode"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.ResultCode = Integer.parseInt(j.toString());
                            }
                        }
                        else if (obj instanceof Integer){
                            this.ResultCode = (Integer)obj;
                        }
                    }
                    continue;
                }

            }

        }



    }

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return this.ResultId!=null?this.ResultId:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==1)
        {
            return this.ResultMessage!=null?this.ResultMessage:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==2)
        {
            return this.IsSuccess!=null?this.IsSuccess:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==3)
        {
            return this.ResultCode!=null?this.ResultCode:SoapPrimitive.NullSkip;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 4;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "ResultId";
            info.namespace= "http://schemas.datacontract.org/2004/07/ResturantService.Result";
        }
        if(propertyIndex==1)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "ResultMessage";
            info.namespace= "http://schemas.datacontract.org/2004/07/ResturantService.Result";
        }
        if(propertyIndex==2)
        {
            info.type = PropertyInfo.BOOLEAN_CLASS;
            info.name = "IsSuccess";
            info.namespace= "http://schemas.datacontract.org/2004/07/ResturantService.Result";
        }
        if(propertyIndex==3)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "ResultCode";
            info.namespace= "http://schemas.datacontract.org/2004/07/ResturantService.Result";
        }
    }
    
    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }

}
