package org.bill.android.myapplication.membershipService;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.5.7.1
//
// Created by Quasar Development at 27/06/2016
//
//---------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;

public class RIVRequestHeader extends AttributeContainer implements KvmSerializable
{

    
    public String Username;
    
    public String Password;
    
    public String Token;

    public RIVRequestHeader ()
    {
    }

    public RIVRequestHeader (java.lang.Object paramObj,RIVExtendedSoapSerializationEnvelope __envelope)
    {
	    
	    if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;


        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                //if you have compilation error here, please use a ksoap2.jar and ExKsoap2.jar from libs folder (in the generated zip file)
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                java.lang.Object obj = info.getValue(); 
                if (info.name.equals("Username"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.Username = j.toString();
                            }
                        }
                        else if (obj instanceof String){
                            this.Username = (String)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("Password"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.Password = j.toString();
                            }
                        }
                        else if (obj instanceof String){
                            this.Password = (String)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("Token"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.Token = j.toString();
                            }
                        }
                        else if (obj instanceof String){
                            this.Token = (String)obj;
                        }
                    }
                    continue;
                }

            }

        }



    }

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return this.Username!=null?this.Username:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==1)
        {
            return this.Password!=null?this.Password:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==2)
        {
            return this.Token!=null?this.Token:SoapPrimitive.NullSkip;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 3;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "Username";
            info.namespace= "http://schemas.datacontract.org/2004/07/ResturantService.Request";
        }
        if(propertyIndex==1)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "Password";
            info.namespace= "http://schemas.datacontract.org/2004/07/ResturantService.Request";
        }
        if(propertyIndex==2)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "Token";
            info.namespace= "http://schemas.datacontract.org/2004/07/ResturantService.Request";
        }
    }
    
    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }

}
